#!/usr/bin/env python3
"""
YTMusic Phone Player - server.py
Runs on Termux, streams audio, serves car-friendly web UI.
"""

import os
import json
import random
import threading
import subprocess
import time
import logging
from pathlib import Path
from flask import Flask, jsonify, request, send_from_directory, Response

# ── Optional: ytmusicapi for account-aware recommendations ──────────────────
try:
    from ytmusicapi import YTMusic
    YTM_AVAILABLE = True
except ImportError:
    YTM_AVAILABLE = False

# ── Optional: yt-dlp for URL resolution ────────────────────────────────────
# yt-dlp must be installed: pip install yt-dlp
import yt_dlp

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("ytplayer")

app = Flask(__name__, template_folder="templates", static_folder="static")

# ═══════════════════════════════════════════════════════════════════════════
# STATE
# ═══════════════════════════════════════════════════════════════════════════

state = {
    "playing":      False,
    "current":      None,       # {title, artist, thumbnail, video_id, duration}
    "queue":        [],         # list of track dicts
    "queue_index":  0,
    "volume":       80,
    "progress":     0,          # seconds elapsed (updated by player thread)
    "shuffle":      True,
    "repeat":       False,
    "source":       "auto",     # "auto" | "liked" | "history" | "search"
    "error":        None,
}

player_proc  = None            # mpv subprocess
player_lock  = threading.Lock()
progress_thread = None

ytm: "YTMusic | None" = None   # authenticated YTMusic client

# ═══════════════════════════════════════════════════════════════════════════
# YTMUSIC AUTH + QUEUE BUILDING
# ═══════════════════════════════════════════════════════════════════════════

AUTH_FILE = Path("oauth.json")   # generated by setup.py


def init_ytmusic():
    global ytm
    if not YTM_AVAILABLE:
        log.warning("ytmusicapi not installed — using unauthenticated mode")
        return
    if AUTH_FILE.exists():
        try:
            ytm = YTMusic(str(AUTH_FILE))
            log.info("YTMusic authenticated ✓")
        except Exception as e:
            log.error(f"YTMusic auth failed: {e}")
            ytm = None
    else:
        log.warning(f"No {AUTH_FILE} found — run setup.py first for account features")


def fetch_liked_songs(limit=100):
    """Fetch liked songs from YT Music account."""
    if ytm is None:
        return []
    try:
        liked = ytm.get_liked_songs(limit=limit)
        tracks = []
        for t in liked.get("tracks", []):
            vid = t.get("videoId")
            if not vid:
                continue
            artists = ", ".join(a["name"] for a in t.get("artists", []))
            tracks.append({
                "video_id":  vid,
                "title":     t.get("title", "Unknown"),
                "artist":    artists or "Unknown Artist",
                "thumbnail": _best_thumb(t.get("thumbnails", [])),
                "duration":  t.get("duration_seconds", 0),
            })
        return tracks
    except Exception as e:
        log.error(f"fetch_liked_songs: {e}")
        return []


def fetch_history(limit=50):
    """Fetch recently played from YT Music account."""
    if ytm is None:
        return []
    try:
        hist = ytm.get_history()
        tracks = []
        for t in hist[:limit]:
            vid = t.get("videoId")
            if not vid:
                continue
            artists = ", ".join(a["name"] for a in t.get("artists", []))
            tracks.append({
                "video_id":  vid,
                "title":     t.get("title", "Unknown"),
                "artist":    artists or "Unknown Artist",
                "thumbnail": _best_thumb(t.get("thumbnails", [])),
                "duration":  t.get("duration_seconds", 0),
            })
        return tracks
    except Exception as e:
        log.error(f"fetch_history: {e}")
        return []


def fetch_recommendations(video_id: str, limit=20):
    """Get radio/recommendations seeded from a video_id."""
    if ytm is None:
        return []
    try:
        radio = ytm.get_watch_playlist(videoId=video_id, radio=True, limit=limit)
        tracks = []
        for t in radio.get("tracks", []):
            vid = t.get("videoId")
            if not vid:
                continue
            artists = ", ".join(a["name"] for a in t.get("artists", []))
            tracks.append({
                "video_id":  vid,
                "title":     t.get("title", "Unknown"),
                "artist":    artists or "Unknown Artist",
                "thumbnail": _best_thumb(t.get("thumbnails", [])),
                "duration":  t.get("duration_seconds", 0),
            })
        return tracks
    except Exception as e:
        log.error(f"fetch_recommendations: {e}")
        return []


def search_tracks(query: str, limit=10):
    """Search YT Music for tracks."""
    if ytm is None:
        # fallback: use yt-dlp search
        return _ytdlp_search(query, limit)
    try:
        results = ytm.search(query, filter="songs", limit=limit)
        tracks = []
        for t in results:
            vid = t.get("videoId")
            if not vid:
                continue
            artists = ", ".join(a["name"] for a in t.get("artists", []))
            tracks.append({
                "video_id":  vid,
                "title":     t.get("title", "Unknown"),
                "artist":    artists or "Unknown Artist",
                "thumbnail": _best_thumb(t.get("thumbnails", [])),
                "duration":  t.get("duration_seconds", 0),
            })
        return tracks
    except Exception as e:
        log.error(f"search_tracks: {e}")
        return _ytdlp_search(query, limit)


def _ytdlp_search(query: str, limit=10):
    """Fallback search via yt-dlp (no auth needed)."""
    try:
        opts = {
            "quiet": True,
            "extract_flat": True,
            "default_search": "ytsearch",
        }
        with yt_dlp.YoutubeDL(opts) as ydl:
            info = ydl.extract_info(f"ytsearch{limit}:{query}", download=False)
        tracks = []
        for entry in info.get("entries", []):
            if not entry:
                continue
            tracks.append({
                "video_id":  entry.get("id", ""),
                "title":     entry.get("title", "Unknown"),
                "artist":    entry.get("uploader", "Unknown Artist"),
                "thumbnail": entry.get("thumbnail", ""),
                "duration":  entry.get("duration", 0),
            })
        return tracks
    except Exception as e:
        log.error(f"_ytdlp_search: {e}")
        return []


def build_auto_queue(seed_id=None, size=40):
    """Build an infinite-feeling mixed queue."""
    liked   = fetch_liked_songs(50)
    history = fetch_history(30)
    recs    = fetch_recommendations(seed_id, 20) if seed_id else []

    pool = liked + history + recs
    # deduplicate by video_id
    seen, unique = set(), []
    for t in pool:
        if t["video_id"] not in seen:
            seen.add(t["video_id"])
            unique.append(t)

    if not unique:
        log.warning("Queue empty — falling back to yt-dlp search for popular music")
        unique = _ytdlp_search("top hits 2024", 20)

    random.shuffle(unique)
    return unique[:size]


def _best_thumb(thumbs):
    if not thumbs:
        return ""
    # pick highest resolution
    return max(thumbs, key=lambda t: t.get("width", 0), default=thumbs[0]).get("url", "")


# ═══════════════════════════════════════════════════════════════════════════
# AUDIO PLAYBACK (mpv)
# ═══════════════════════════════════════════════════════════════════════════

def resolve_audio_url(video_id: str) -> str | None:
    """Use yt-dlp to get the best audio-only URL."""
    ydl_opts = {
        "quiet":   True,
        "format":  "bestaudio/best",
        "noplaylist": True,
    }
    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(
                f"https://www.youtube.com/watch?v={video_id}",
                download=False
            )
        # prefer audio-only formats
        for fmt in sorted(info.get("formats", []), key=lambda f: f.get("abr", 0) or 0, reverse=True):
            if fmt.get("vcodec") == "none" and fmt.get("url"):
                return fmt["url"]
        return info.get("url")
    except Exception as e:
        log.error(f"resolve_audio_url({video_id}): {e}")
        return None


def play_track(track: dict):
    """Kill current player, resolve URL, launch mpv for audio-only."""
    global player_proc

    with player_lock:
        _kill_player()
        state["playing"]  = True
        state["current"]  = track
        state["progress"] = 0
        state["error"]    = None

    log.info(f"▶ {track['title']} — {track['artist']}")

    url = resolve_audio_url(track["video_id"])
    if not url:
        state["error"]   = "Could not resolve audio URL"
        state["playing"] = False
        auto_next()
        return

    # mpv: no video, audio only, respect volume
    cmd = [
        "mpv",
        "--no-video",
        "--really-quiet",
        f"--volume={state['volume']}",
        "--term-status-msg=",
        url,
    ]
    with player_lock:
        player_proc = subprocess.Popen(
            cmd,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )

    # watch for track end in background
    threading.Thread(target=_watch_player, daemon=True).start()
    # update progress
    threading.Thread(target=_track_progress, args=(track.get("duration", 0),), daemon=True).start()


def _kill_player():
    global player_proc
    if player_proc and player_proc.poll() is None:
        player_proc.terminate()
        try:
            player_proc.wait(timeout=3)
        except subprocess.TimeoutExpired:
            player_proc.kill()
    player_proc = None


def _watch_player():
    """Wait for mpv to finish, then auto-advance."""
    global player_proc
    if player_proc:
        player_proc.wait()
    if state["playing"]:
        auto_next()


def _track_progress(duration: int):
    """Update progress counter every second while playing."""
    start = time.time()
    while state["playing"] and player_proc and player_proc.poll() is None:
        state["progress"] = int(time.time() - start)
        time.sleep(1)


def auto_next():
    """Advance queue, refill if near end."""
    q   = state["queue"]
    idx = state["queue_index"]

    if state["repeat"] and state["current"]:
        play_track(state["current"])
        return

    next_idx = idx + 1

    # refill queue when near the end
    if next_idx >= len(q) - 5:
        seed = state["current"]["video_id"] if state["current"] else None
        more = build_auto_queue(seed_id=seed, size=20)
        # add only new ones
        existing_ids = {t["video_id"] for t in q}
        for t in more:
            if t["video_id"] not in existing_ids:
                q.append(t)

    if next_idx < len(q):
        state["queue_index"] = next_idx
        play_track(q[next_idx])
    else:
        state["playing"] = False
        state["current"] = None


# ═══════════════════════════════════════════════════════════════════════════
# FLASK ROUTES — API
# ═══════════════════════════════════════════════════════════════════════════

@app.route("/api/state")
def api_state():
    return jsonify({
        "playing":    state["playing"],
        "current":    state["current"],
        "queue":      state["queue"][state["queue_index"]:state["queue_index"]+5],
        "volume":     state["volume"],
        "progress":   state["progress"],
        "shuffle":    state["shuffle"],
        "repeat":     state["repeat"],
        "error":      state["error"],
        "ytm_auth":   ytm is not None,
    })


@app.route("/api/play", methods=["POST"])
def api_play():
    data = request.json or {}
    vid  = data.get("video_id")

    if vid:
        # play specific video_id
        # find in queue or prepend
        q = state["queue"]
        for i, t in enumerate(q):
            if t["video_id"] == vid:
                state["queue_index"] = i
                play_track(t)
                return jsonify({"ok": True})
        # not in queue — create a minimal track
        track = {
            "video_id":  vid,
            "title":     data.get("title", "Unknown"),
            "artist":    data.get("artist", ""),
            "thumbnail": data.get("thumbnail", ""),
            "duration":  data.get("duration", 0),
        }
        q.insert(state["queue_index"] + 1, track)
        state["queue_index"] += 1
        play_track(track)
    else:
        # resume / start queue
        q = state["queue"]
        if not q:
            threading.Thread(target=_init_queue_and_play, daemon=True).start()
            return jsonify({"ok": True, "msg": "Building queue…"})
        idx = state["queue_index"]
        if idx < len(q):
            play_track(q[idx])

    return jsonify({"ok": True})


def _init_queue_and_play():
    q = build_auto_queue(size=40)
    state["queue"]       = q
    state["queue_index"] = 0
    if q:
        play_track(q[0])


@app.route("/api/pause", methods=["POST"])
def api_pause():
    with player_lock:
        if player_proc and player_proc.poll() is None:
            # mpv doesn't easily pause via subprocess; send SIGSTOP
            import signal
            try:
                player_proc.send_signal(signal.SIGSTOP)
                state["playing"] = False
            except Exception:
                pass
    return jsonify({"ok": True})


@app.route("/api/resume", methods=["POST"])
def api_resume():
    with player_lock:
        if player_proc and player_proc.poll() is None:
            import signal
            try:
                player_proc.send_signal(signal.SIGCONT)
                state["playing"] = True
            except Exception:
                pass
        else:
            # restart
            q   = state["queue"]
            idx = state["queue_index"]
            if idx < len(q):
                play_track(q[idx])
    return jsonify({"ok": True})


@app.route("/api/next", methods=["POST"])
def api_next():
    threading.Thread(target=auto_next, daemon=True).start()
    return jsonify({"ok": True})


@app.route("/api/prev", methods=["POST"])
def api_prev():
    idx = state["queue_index"]
    if idx > 0:
        state["queue_index"] = idx - 1
        threading.Thread(target=lambda: play_track(state["queue"][state["queue_index"]]), daemon=True).start()
    return jsonify({"ok": True})


@app.route("/api/volume", methods=["POST"])
def api_volume():
    vol = int(request.json.get("volume", 80))
    vol = max(0, min(100, vol))
    state["volume"] = vol
    # live-adjust mpv if possible (via IPC would be ideal; for now restart is not needed)
    # mpv doesn't support volume change via Popen easily without IPC socket
    # We store it and apply on next track start
    return jsonify({"ok": True, "volume": vol})


@app.route("/api/search")
def api_search():
    q = request.args.get("q", "").strip()
    if not q:
        return jsonify({"results": []})
    results = search_tracks(q, limit=12)
    return jsonify({"results": results})


@app.route("/api/queue/refresh", methods=["POST"])
def api_refresh_queue():
    seed = state["current"]["video_id"] if state["current"] else None
    threading.Thread(target=lambda: _rebuild_queue(seed), daemon=True).start()
    return jsonify({"ok": True, "msg": "Refreshing queue…"})


def _rebuild_queue(seed=None):
    q = build_auto_queue(seed_id=seed, size=40)
    state["queue"]       = q
    state["queue_index"] = 0


@app.route("/api/toggle/shuffle", methods=["POST"])
def api_shuffle():
    state["shuffle"] = not state["shuffle"]
    if state["shuffle"]:
        # re-shuffle remaining queue
        remaining = state["queue"][state["queue_index"]+1:]
        random.shuffle(remaining)
        state["queue"] = state["queue"][:state["queue_index"]+1] + remaining
    return jsonify({"shuffle": state["shuffle"]})


@app.route("/api/toggle/repeat", methods=["POST"])
def api_repeat():
    state["repeat"] = not state["repeat"]
    return jsonify({"repeat": state["repeat"]})


# ═══════════════════════════════════════════════════════════════════════════
# FLASK ROUTES — UI
# ═══════════════════════════════════════════════════════════════════════════

@app.route("/")
def index():
    return send_from_directory("templates", "index.html")


@app.route("/static/<path:filename>")
def static_files(filename):
    return send_from_directory("static", filename)


# ═══════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    init_ytmusic()
    # pre-build queue in background
    threading.Thread(target=_init_queue_and_play, daemon=True).start()
    log.info("🎵 YTMusic Phone Player starting on http://0.0.0.0:5000")
    app.run(host="0.0.0.0", port=5000, debug=False, threaded=True)
